// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABT_iHwUob7fUOVmTFUYP7pJ5pDAJu6EA',
    appId: '1:862681026576:web:1cbc6638e773d5641cba95',
    messagingSenderId: '862681026576',
    projectId: 'khelset-new',
    authDomain: 'khelset-new.firebaseapp.com',
    storageBucket: 'khelset-new.firebasestorage.app',
    measurementId: 'G-XRH5NW1EM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYtRzO3mlfGy8-ntMzLAkPZy2USJwViQ',
    appId: '1:862681026576:android:3be9499b4c5bef091cba95',
    messagingSenderId: '862681026576',
    projectId: 'khelset-new',
    storageBucket: 'khelset-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYtRzO3mlfGy8-ntMzLAkPZy2USJwViQ',
    appId: '1:862681026576:ios:3be9499b4c5bef091cba95',
    messagingSenderId: '862681026576',
    projectId: 'khelset-new',
    storageBucket: 'khelset-new.firebasestorage.app',
    androidClientId: '862681026576-0hktrf850btf29ckj6m4h7mktrq0p0e5.apps.googleusercontent.com',
    iosClientId: '862681026576-i119a8hem93giu3qq0cive18vudrc7qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJYtRzO3mlfGy8-ntMzLAkPZy2USJwViQ',
    appId: '1:862681026576:ios:3be9499b4c5bef091cba95',
    messagingSenderId: '862681026576',
    projectId: 'khelset-new',
    storageBucket: 'khelset-new.firebasestorage.app',
    androidClientId: '862681026576-0hktrf850btf29ckj6m4h7mktrq0p0e5.apps.googleusercontent.com',
    iosClientId: '862681026576-i119a8hem93giu3qq0cive18vudrc7qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABT_iHwUob7fUOVmTFUYP7pJ5pDAJu6EA',
    appId: '1:862681026576:web:1cbc6638e773d5641cba95',
    messagingSenderId: '862681026576',
    projectId: 'khelset-new',
    authDomain: 'khelset-new.firebaseapp.com',
    storageBucket: 'khelset-new.firebasestorage.app',
    measurementId: 'G-XRH5NW1EM7',
  );

}