// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjyN6idJU_jtbjKWTwx21bNNtCk66ogc',
    appId: '1:412114553058:web:33351422587acb9992b6bb',
    messagingSenderId: '412114553058',
    projectId: 'khelset-e8a8c',
    authDomain: 'khelset-e8a8c.firebaseapp.com',
    storageBucket: 'khelset-e8a8c.firebasestorage.app',
    measurementId: 'G-1V6PVQME41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMuM2stCIE49Qd67ybq1hYCFO_2oNnAis',
    appId: '1:412114553058:android:4077fd0446628c5392b6bb',
    messagingSenderId: '412114553058',
    projectId: 'khelset-e8a8c',
    storageBucket: 'khelset-e8a8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8N03a_-KqXoIwuButMnGDpWizQ8gyVM0',
    appId: '1:412114553058:ios:474a2c2086fad9b992b6bb',
    messagingSenderId: '412114553058',
    projectId: 'khelset-e8a8c',
    storageBucket: 'khelset-e8a8c.firebasestorage.app',
    androidClientId: '412114553058-0hktrf850btf29ckj6m4h7mktrq0p0e5.apps.googleusercontent.com',
    iosClientId: '412114553058-i119a8hem93giu3qq0cive18vudrc7qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8N03a_-KqXoIwuButMnGDpWizQ8gyVM0',
    appId: '1:412114553058:ios:474a2c2086fad9b992b6bb',
    messagingSenderId: '412114553058',
    projectId: 'khelset-e8a8c',
    storageBucket: 'khelset-e8a8c.firebasestorage.app',
    androidClientId: '412114553058-0hktrf850btf29ckj6m4h7mktrq0p0e5.apps.googleusercontent.com',
    iosClientId: '412114553058-i119a8hem93giu3qq0cive18vudrc7qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjyN6idJU_jtbjKWTwx21bNNtCk66ogc',
    appId: '1:412114553058:web:2a4ea74be882e2f292b6bb',
    messagingSenderId: '412114553058',
    projectId: 'khelset-e8a8c',
    authDomain: 'khelset-e8a8c.firebaseapp.com',
    storageBucket: 'khelset-e8a8c.firebasestorage.app',
    measurementId: 'G-H9SP43QX20',
  );

}